### ISSUE TITLE
Use gas carrier temperature

### ISSUE THREAD

**Issue by KobusVanRooyen** [Project-OMOTES/rtc-tools-heat-network#127]
Currently a default hard-coded value for the gas temperature of 20 degrees Celsius is used, but this should change to a value specified for the gas carrier

**Comment by jimrojerTNO** [comment]
@KobusVanRooyen we should add Edwin and Ewoud here if we want an additional attribute in the carreri

**Comment by jimrojerTNO** [comment]
@octavianor for gas networks, do they have a sort of a reference operating temperature? Or does that vary throughout the network?

Reason why we are asking is if there should be also a temperature attribute for the gas carrier in ESDL

**Comment by KobusVanRooyen** [comment]
Thanks @octavianor. For now this functionality is then not required and it will be a hard-coded setting in the code
