### ISSUE TITLE
Confirm inclusion of "heat_exchanger_elec" & "pump"  in "annualized"

### ISSUE THREAD

**Issue by KobusVanRooyen** [Project-OMOTES/rtc-tools-heat-network#128]
During the merge of branch 113 back to master there was a code conflict in minimize_tco_goal.py. Confirmation is required if "heat_exchanger_elec" & "pump" must be included in the "annualized" dictionary as implemented during the conflict resolution.

**Comment by jimrojerTNO** [comment]
heat_exchanger_elec should be out, pump should be in
