### ISSUE TITLE
Time zone setting

### ISSUE THREAD

**Issue by KobusVanRooyen** [Project-OMOTES/rtc-tools-heat-network#70]
Time zones will not always be set automatically, for example a constant heating demand vs profile (from database) heating demand. A time zone would be added for the case with a constant demand, but not for the case with a demand profile. This problem was noticed when the variable self.io.datetimes[__] was used during the write out of variable data to a influxDB.  So it seems that the date time variable assignment in esdl_mixin.py is not consistent.

**Comment by jimrojerTNO** [comment]
this should be checked if this is still a problem in the new profile_parser concept that Thijs made

**Comment by KobusVanRooyen** [comment]
Resolved in MESIDO git repo
